[package]
name = "joshuaclarkelua/red"
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = [
	"default.project.json",
	"lib",
	"lib/**",
	"LICENSE",
	"wally.toml",
	"README.md",
]

[dependencies]
Signal = "red-blox/signal@^2.0.0"
Spawn = "red-blox/spawn@^1.0.0"
Guard = "red-blox/guard@^1.0.0"
Promise = "joshuaclarkelua/promise@4.0.12"
